import { useEffect, useState } from "react"
import {
  Links,
  Meta,
  Outlet,
  Scripts,
  ScrollRestoration,
  isRouteErrorResponse,
} from "react-router"
import { WarningOctagonIcon } from "@phosphor-icons/react"
import { PageTransitionProvider } from "~/components/PageTransitionProvider"

import type { Route } from "./+types/root"
import "./app.css"
import { TooltipProvider } from "./components/ui/tooltip"

// Register the service worker generated by vite-plugin-pwa.
// Only in production — the file doesn't exist in dev mode and would 404.
if (
  import.meta.env.PROD &&
  typeof window !== "undefined" &&
  "serviceWorker" in navigator
) {
  window.addEventListener("load", () => {
    navigator.serviceWorker
      .register("/sw.js", { scope: "/" })
      .catch((err) => console.warn("[SW] Registration failed:", err))
  })
}

export function Layout({ children }: { children: React.ReactNode }) {
  const [isLoaderMounted, setIsLoaderMounted] = useState(true)
  const [isLoaderFading, setIsLoaderFading] = useState(false)

  useEffect(() => {
    setIsLoaderFading(true)
    // Keep this lifecycle in React. Removing #js-loader directly from the DOM
    // leaves React holding a stale child reference; a later layout update then
    // attempts a second removal and throws a NotFoundError.
    const timer = window.setTimeout(() => setIsLoaderMounted(false), 400)
    return () => window.clearTimeout(timer)
  }, [])

  return (
    <html lang="en" className="h-full">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#0a0a1e" />
        {/* Kept in the static SPA shell because many social crawlers do not run JavaScript. */}
        <title>Fog of Walk — Explore the unknown</title>
        <meta
          name="description"
          content="Import your GPX and FIT activity files. Watch the fog of war lift over every trail you've run, every road you've cycled, every path you've ever walked."
        />
        <link rel="canonical" href="https://fog-of-walk.mykhailo.net/" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="Fog of Walk — Explore the unknown" />
        <meta
          property="og:description"
          content="Import your GPX and FIT activity files. Watch the fog of war lift over every trail you've run, every road you've cycled, every path you've ever walked."
        />
        <meta property="og:url" content="https://fog-of-walk.mykhailo.net/" />
        <meta property="og:site_name" content="Fog of Walk" />
        <meta
          property="og:image"
          content="https://fog-of-walk.mykhailo.net/og-image.png"
        />
        <meta property="og:image:type" content="image/png" />
        <meta property="og:image:width" content="1200" />
        <meta property="og:image:height" content="630" />
        <meta
          property="og:image:alt"
          content="Fog of Walk — Explore the unknown"
        />
        <meta name="twitter:card" content="summary_large_image" />
        <meta
          name="twitter:title"
          content="Fog of Walk — Explore the unknown"
        />
        <meta
          name="twitter:description"
          content="Import your GPX and FIT activity files. Watch the fog of war lift over every trail you've run, every road you've cycled, every path you've ever walked."
        />
        <meta
          name="twitter:image"
          content="https://fog-of-walk.mykhailo.net/og-image.png"
        />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
        <link rel="alternate icon" href="/favicon.ico" />
        <link rel="manifest" href="/site.webmanifest" />
        <link
          rel="apple-touch-icon"
          sizes="192x192"
          href="/icons/icon-192.png"
        />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta
          name="apple-mobile-web-app-status-bar-style"
          content="black-translucent"
        />
        <meta name="apple-mobile-web-app-title" content="Fog of Walk" />
        <Meta />
        <Links />
      </head>
      <body className="h-full bg-[#0a0a1e]">
        {isLoaderMounted && (
          <div
            id="js-loader"
            role="status"
            aria-label="Loading Fog of Walk"
            style={{ opacity: isLoaderFading ? 0 : 1 }}
          >
            <h1>Fog of Walk</h1>
            <div className="fow-spinner" />
          </div>
        )}
        <TooltipProvider>{children}</TooltipProvider>
        <ScrollRestoration />
        <Scripts />
      </body>
    </html>
  )
}

export default function App() {
  return (
    <PageTransitionProvider>
      <Outlet />
    </PageTransitionProvider>
  )
}

export function ErrorBoundary({ error }: Route.ErrorBoundaryProps) {
  let title = "Something went wrong"
  let message = "An unexpected error occurred."
  let stack: string | undefined

  if (isRouteErrorResponse(error)) {
    title = error.status === 404 ? "Page not found" : `Error ${error.status}`
    message =
      error.status === 404
        ? "The requested page could not be found."
        : error.statusText || message
  } else if (error instanceof Error) {
    message = import.meta.env.DEV ? error.message : message
    stack = import.meta.env.DEV ? error.stack : undefined
  }

  return (
    <div className="relative flex h-screen w-screen items-center justify-center overflow-hidden bg-background">
      {/* subtle fog-like radial gradient in the background */}
      <div
        className="pointer-events-none absolute inset-0 opacity-40"
        style={{
          background:
            "radial-gradient(ellipse 80% 60% at 50% 50%, #1a1a3e 0%, #0a0a1e 100%)",
        }}
      />
      <div className="relative z-10 flex w-full max-w-sm flex-col gap-4 px-4">
        <div className="flex items-center gap-3">
          <WarningOctagonIcon
            weight="duotone"
            size={28}
            className="shrink-0 text-destructive"
          />
          <h1 className="font-heading text-base font-medium">{title}</h1>
        </div>
        <p className="text-xs/relaxed text-muted-foreground">{message}</p>
        {stack && (
          <pre className="max-h-48 overflow-auto rounded-none border border-foreground/10 bg-card/60 p-3 text-xs text-muted-foreground">
            {stack}
          </pre>
        )}
        <button
          onClick={() => window.location.reload()}
          className="w-fit cursor-pointer border border-foreground/15 bg-card/60 px-3 py-1.5 text-xs backdrop-blur-md transition-colors hover:bg-card"
        >
          Reload
        </button>
      </div>
    </div>
  )
}
